development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Disser
  admin_email: jastix@mail.ru

test:
  <<: *non_production_settings

staging:
  site_url: http://staging.example.com
  site_name: Bort
  admin_email: bort@bort.com

production:
  site_url: http://localhost
  site_name: Disser
  admin_email: jastix@mail.ru
